[project]
name = "profile-service"
version = "0.1.1"
description = "Nexus microservice"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.0",
    "email-validator>=2.2.0",
    "fastapi[standard]>=0.139.2",
    "psycopg[binary]>=3.2.0",
    "pydantic-settings>=2.10.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.0",
]

[tool.semantic_release]
allow_zero_version = true
commit_parser = "conventional-monorepo"
commit_message = "chore(release): profile-service-v{version} [skip ci]"
major_on_zero = false
tag_format = "profile-service-v{version}"
version_toml = ["pyproject.toml:project.version"]

[tool.semantic_release.commit_parser_options]
path_filters = ["."]
scope_prefix = "profile"
patch_tags = ["fix", "perf", "deps"]
allowed_tags = ["feat", "fix", "perf", "deps", "build", "chore", "ci", "docs", "style", "refactor", "test"]
