[project]
name = "auth-service"
version = "0.1.12"
description = "Nexus microservice"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.43.60",
    "email-validator>=2.2.0",
    "fastapi[standard]>=0.141.1",
    "psycopg[binary]>=3.2.0",
    "pydantic-settings>=2.10.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.0",
]

[tool.semantic_release]
allow_zero_version = true
commit_parser = "conventional-monorepo"
commit_message = "chore(release): auth-service-v{version} [skip ci]"
major_on_zero = false
tag_format = "auth-service-v{version}"
version_toml = ["pyproject.toml:project.version"]

[tool.semantic_release.commit_parser_options]
path_filters = ["."]
scope_prefix = "auth"
patch_tags = ["fix", "perf", "revert", "deps"]
allowed_tags = ["feat", "fix", "perf", "revert", "deps", "build", "chore", "ci", "docs", "style", "refactor", "test"]
