name: Dependabot auto-merge

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read

jobs:
  enable-auto-merge:
    name: Enable Dependabot auto-merge
    if: >-
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      github.repository == 'nguyentin05/nexus-app'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Metadata from Dependabot PRs
        id: metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for patch updates
        id: auto-merge
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        env:
          GH_TOKEN: ${{ secrets.NEXUS_CICD_BOT_TOKEN }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: gh pr merge --auto --squash --subject "$PR_TITLE" --body "Automated patch dependency update." "$PR_URL"
